// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBmdYwtbeIq0AOSQVUL88ty2GfwvJb7Q8',
    appId: '1:956424255593:web:4bdd6f4ec836ad71470af8',
    messagingSenderId: '956424255593',
    projectId: 'healify-b433f',
    authDomain: 'healify-b433f.firebaseapp.com',
    storageBucket: 'healify-b433f.appspot.com',
    measurementId: 'G-NL8S6SJRGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAGJen33y3f9GmiEO_OUqcQrpPsNzKKA',
    appId: '1:956424255593:android:a05b4b0fba7f0b85470af8',
    messagingSenderId: '956424255593',
    projectId: 'healify-b433f',
    storageBucket: 'healify-b433f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUh0nSInHZ2v_ZBnXLwkIKJRNGVMEzAMM',
    appId: '1:956424255593:ios:c81aad4cd55899e1470af8',
    messagingSenderId: '956424255593',
    projectId: 'healify-b433f',
    storageBucket: 'healify-b433f.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUh0nSInHZ2v_ZBnXLwkIKJRNGVMEzAMM',
    appId: '1:956424255593:ios:c81aad4cd55899e1470af8',
    messagingSenderId: '956424255593',
    projectId: 'healify-b433f',
    storageBucket: 'healify-b433f.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBmdYwtbeIq0AOSQVUL88ty2GfwvJb7Q8',
    appId: '1:956424255593:web:a0088078e61b1ffa470af8',
    messagingSenderId: '956424255593',
    projectId: 'healify-b433f',
    authDomain: 'healify-b433f.firebaseapp.com',
    storageBucket: 'healify-b433f.appspot.com',
    measurementId: 'G-P3FD1WZB9Z',
  );

}